/* Wrapper TU for pcre2_study.c — generated by native/refresh-pcre2.sh, do not edit.
 *
 * vytoc compiles native/src/*.c flat with a fixed command line and has no
 * #cflags pragma, so PCRE2's two required defines are set here rather than on
 * the compiler invocation. Everything else comes from native/src/config.h.
 *
 * Do NOT merge these wrappers into one unity build: upstream has many
 * same-named file statics, and collapsing the translation units makes them
 * collide. */
#define PCRE2_CODE_UNIT_WIDTH 8
#define HAVE_CONFIG_H
#include "pcre2/src/pcre2_study.c"
