#!/bin/sh
# Provision OpenSSL for vyto/crypto/openssl on a target with no system copy.
#
# Linux links the distro's libssl-dev (#link "ssl" / "crypto" in openssl.vt), so
# nothing here is needed there. macOS and Windows both need this:
#
#   macOS   ships libssl.dylib but NO headers, and Homebrew's live under a
#           prefix vytoc cannot be told about — there is no #cflags pragma, and
#           the only include paths a shim gets are native/src and
#           native/<triple>/include (src/main.c).
#   Windows has no system OpenSSL at all.
#
# What this installs, per triple:
#   native/<triple>/include/openssl/*.h    headers (vytoc adds -I for the triple)
#   native/<triple>/libssl*, libcrypto*    the library itself, supplied by you
#
# ── WHY THIS DOES NOT DOWNLOAD A TARBALL ────────────────────────────────────
# provision-curl.sh fetches curl's headers from the release tarball and that is
# correct for curl. It would be WRONG here. OpenSSL's opensslconf.h and
# configuration.h are GENERATED BY Configure and encode the options that build
# was made with — no-deprecated, the thread model, the assembler choice, the
# integer widths. Headers from a generic tarball are not the headers your
# libcrypto was built with, and the resulting mismatch is silent: it compiles,
# it links, and it goes wrong at runtime in a struct layout.
#
# So the headers come from the SAME tree as the binary, and this script's job is
# to copy them there and prove they match. Point it at a built or installed
# prefix with --from.
#
# Usage:
#   provision-openssl.sh macos-arm64 --from /opt/homebrew/opt/openssl@3
#   provision-openssl.sh windows-x64 --from ~/openssl-3.0.15-win64
#   provision-openssl.sh macos-arm64 --check     # validate what is already there
#
# The binaries are NOT committed (*.dll and *.dylib are gitignored); they ship
# with a Vyto release, exactly as libcurl's DLL does.
set -e

TRIPLE=""
FROM=""
CHECK_ONLY=0

# OpenSSL 3.0. The 1.1 -> 3.x soname change is not ABI-compatible and 3.x
# deprecated the low-level APIs the shim would otherwise need two paths for;
# ossl_shim.c refuses to compile below this with an #error, and this is the
# same floor checked earlier, where the message can be useful.
MIN_MAJOR=3

while [ $# -gt 0 ]; do
    case "$1" in
        --check) CHECK_ONLY=1 ;;
        --from)  shift; FROM="$1" ;;
        -*)      echo "unknown option: $1" >&2; exit 2 ;;
        *)       TRIPLE="$1" ;;
    esac
    shift
done

[ -n "$TRIPLE" ] || { echo "usage: provision-openssl.sh <triple> [--from <prefix>] [--check]" >&2; exit 2; }

HERE="$(cd "$(dirname "$0")" && pwd)"
DEST="$HERE/$TRIPLE"
say() { echo "[vyto/crypto/openssl] $*"; }

# The version the headers claim. This is the number that has to satisfy the
# floor, because it is the one the shim compiles against.
header_version() {
    v="$(sed -n 's/^# *define  *OPENSSL_VERSION_STR  *"\([^"]*\)".*/\1/p' \
         "$1/openssl/opensslv.h" 2>/dev/null | head -n1)"
    echo "$v"
}

check_dest() {
    inc="$DEST/include"
    if [ ! -f "$inc/openssl/ssl.h" ]; then
        say "no headers in $inc/openssl — run with --from <prefix>"
        return 1
    fi
    # opensslconf.h is the generated one. Its absence means someone copied the
    # source tree's include/ rather than an installed or built prefix, and that
    # tree does not have it yet.
    if [ ! -f "$inc/openssl/opensslconf.h" ]; then
        say "!! opensslconf.h is missing. Two things cause this:"
        say "   - the headers came from an unconfigured SOURCE tree rather than"
        say "     a build, so the generated ones do not exist yet; or"
        say "   - a Debian-style multiarch prefix, which puts opensslconf.h in"
        say "     include/<arch>/openssl/ and leaves the rest in include/openssl/."
        say "   Either way these headers cannot be trusted to match a libcrypto."
        say "   Use the prefix of an actual build (the one with lib/ beside"
        say "   include/), and copy the generated header in from wherever it landed."
        return 1
    fi
    ver="$(header_version "$inc")"
    if [ -z "$ver" ]; then
        say "!! could not read OPENSSL_VERSION_STR from opensslv.h"
        return 1
    fi
    major="${ver%%.*}"
    if [ "$major" -lt "$MIN_MAJOR" ] 2>/dev/null; then
        say "!! headers are OpenSSL $ver; this package requires $MIN_MAJOR.0 or newer."
        say "   ossl_shim.c will refuse to compile, which is the intended outcome."
        return 1
    fi
    say "headers: OpenSSL $ver in $inc/openssl"

    libs="$(ls "$DEST"/libssl* "$DEST"/libcrypto* "$DEST"/*ssl*.dll "$DEST"/*crypto*.dll \
            2>/dev/null || true)"
    if [ -z "$libs" ]; then
        say "!! no libssl/libcrypto in $DEST."
        say "   Copy them from the same prefix these headers came from, or take"
        say "   them from a Vyto release. Headers and binary MUST be one build."
        return 1
    fi
    for l in $libs; do say "library: $(basename "$l")"; done

    # A static archive needs its transitive -l flags spelled out for --bundle;
    # main.c reads them from a .deps sidecar next to the .a.
    for a in "$DEST"/libssl.a "$DEST"/libcrypto.a; do
        if [ -f "$a" ] && [ ! -f "$a.deps" ]; then
            say "!! $(basename "$a") has no $(basename "$a").deps sidecar."
            say "   A static OpenSSL needs its own dependencies on the link line"
            say "   (-lpthread -ldl on POSIX; -lws2_32 -lcrypt32 -lbcrypt -ladvapi32"
            say "   -luser32 on Windows). Write them one per line into that file."
        fi
    done
    say "done checking."
    return 0
}

if [ "$CHECK_ONLY" = 1 ]; then
    check_dest
    exit $?
fi

[ -n "$FROM" ] || { echo "--from <prefix> is required (or use --check)" >&2; exit 2; }
[ -d "$FROM/include/openssl" ] || {
    echo "no include/openssl under $FROM — that is not an OpenSSL prefix" >&2; exit 1; }

srcver="$(header_version "$FROM/include")"
say "installing OpenSSL ${srcver:-?} headers for $TRIPLE from $FROM…"

# Per-triple, never native/src: that directory is shared by every target, so
# headers left there would shadow the system OpenSSL on Linux too.
rm -rf "$DEST/include/openssl"
mkdir -p "$DEST/include/openssl"
cp "$FROM/include/openssl/"*.h "$DEST/include/openssl/"

say "installed $(ls "$DEST/include/openssl" | wc -l | tr -d ' ') headers in $DEST/include/openssl"

# The binaries are copied from the SAME prefix when they are there, because
# headers and binary matching is the whole point of this script.
copied=0
for pat in libssl.3.dylib libssl.dylib libcrypto.3.dylib libcrypto.dylib \
           libssl-3-x64.dll libcrypto-3-x64.dll libssl.dll libcrypto.dll; do
    if [ -f "$FROM/lib/$pat" ]; then cp "$FROM/lib/$pat" "$DEST/"; copied=$((copied + 1)); fi
    if [ -f "$FROM/bin/$pat" ]; then cp "$FROM/bin/$pat" "$DEST/"; copied=$((copied + 1)); fi
done
[ "$copied" -gt 0 ] && say "copied $copied librar(y|ies) from $FROM"

check_dest
