/* Wrapper TU for zlib's trees.c — see ../../README.md, "Why zlib is vendored".
 *
 * GENERATED by native/refresh-zlib.sh. Do not edit; edit that script.
 *
 * vytoc globs native/src/*.c FLAT and non-recursively (src/main.c:1030-1046),
 * so native/src/zlib/ is invisible to the build. Each upstream source needs one
 * of these to be compiled at all, and the only include path is -Inative/src
 * (src/main.c:1043), which is what makes the relative include below resolve.
 *
 * One wrapper per upstream TU, never a unity build: zlib has same-named file
 * statics that collide when translation units are merged.
 *
 * The build options come from zlib_config.h, which zlib_shim.c includes too —
 * Z_SOLO changes which prototypes zlib.h declares, so the shim and the library
 * must be compiled with the same view of it.
 *
 * --freestanding splices -DVT_NO_LIBC into every package shim's compile line
 * (src/main.c:878-879). zlib needs an allocator, so there is nothing to degrade
 * to: the whole library drops out and zlib_shim.c's stub arm answers instead.
 * Same arrangement as lib/vyto/db/sqlite/native/src/vsqlite3.c:16-23.
 */
#ifndef VT_NO_LIBC
#include "zlib_config.h"
#include "zlib/trees.c"
#endif
